/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagramfinder

import anagramfinder.services.*
import kotlinx.cli.ArgParser
import kotlinx.cli.ArgType

class App {
    companion object {
        const val appName = "AnagramFinder CLI App"
    }
}

fun main(args: Array<String>) {
    val parser = ArgParser(App.appName)
    val inputFile by parser.argument(ArgType.String, description = "Input file")
    val outputFile by parser.option(ArgType.String, shortName = "o", description = "Output file")

    parser.parse(args)


    ErrorManager().run {
        FileUtils.readFile(inputFile)
            .let { InputParser.parse(it) }
            .let { GraphRelationshipsComputer.compute(it) }
            .let { GraphFormatter().format(it) }
            .let {
                if (!outputFile.isNullOrBlank()) {
                    FileUtils.writeToFile(outputFile!!, it)
                } else {
                    println(it)
                }
            }
    }
}
