/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagramfinder

import kotlinx.cli.ArgParser
import kotlinx.cli.ArgType

class App {
    companion object {
        const val appName = "AnagramFinder CLI App"
        const val version = "0.0.2"
    }
}

fun main(args: Array<String>) {
    val parser = ArgParser("${App.appName}:: ${App.version}")
    val version by parser.option(ArgType.Boolean, shortName = "v", description = "Version", fullName = "version")

    // Add all input to parser
    parser.parse(args)

    if(version == true) println(App.version)
}
